path: C:\Users\Lenovo\OIDv4_ToolKit\OID\Dataset
train: images/train
val: images/validation

names:
  0: Penguin


augment:
  flipud: 0.5
  fliplr: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 10.0
  translate: 0.1
  scale: 0.5
  shear: 2.0
  perspective: 0.0
